report = """===============================================================================
              KNOWLEDGE GRAPH GUIDED RADIOLOGY REPORT EVALUATION
===============================================================================

Case Information
===============================================================================

Image ID      : image_0196.png

Image Location:
data/mimic_cxr_images/image_0196.png


===============================================================================
1. GROUND TRUTH REPORT
===============================================================================

Findings
--------
Minimally displaced fracture of the right sixth posterior rib.
Possible fracture of the right fifth lateral rib.
No pleural effusion.
No pneumothorax.
Cardiomediastinal silhouette is within normal limits.

Impression
----------
Right-sided fifth and sixth rib fractures without evidence of
pneumothorax or other acute cardiopulmonary abnormality.


===============================================================================
2. CHEXAGENT GENERATED REPORT
===============================================================================

Findings
--------
Cardiomediastinal silhouette is within normal limits.
No focal air-space consolidation.
No pleural effusion.
No pneumothorax.
No acute cardiopulmonary process identified.

Impression
----------
No acute cardiopulmonary abnormality.

===============================================================================
3. KNOWLEDGE GRAPH REVIEW
===============================================================================

Clinical Interpretation
-----------------------
• Possible right posterior rib fracture detected.

• Possible right lateral rib fracture identified.

Additional Findings Requiring Review
------------------------------------
• Right sixth posterior rib fracture.

• Right fifth lateral rib fracture.

Potential Unsupported Findings
------------------------------
The following concepts generated by CheXagent were not supported by the
reference Knowledge Graph.

• acute cardiopulmonary process

Knowledge Graph Summary
-----------------------

Missing Findings           : 2

Unsupported Findings       : 1

Missing Relations          : 2

Unsupported Relations      : 0


===============================================================================
4. HYBRID CORRECTOR (CHEXAGENT + KNOWLEDGE GRAPH)
===============================================================================

The Hybrid Corrector combines the CheXagent-generated report with
Knowledge Graph reasoning. Missing findings detected by the Knowledge
Graph are incorporated while unsupported observations are removed,
resulting in a clinically more complete report.

Corrected Findings
------------------
Cardiomediastinal silhouette is within normal limits.
Minimally displaced fracture of the right sixth posterior rib.
Possible fracture involving the right fifth lateral rib.
No pleural effusion.
No pneumothorax.

Corrected Impression
--------------------
Right fifth and sixth rib fractures without evidence of pneumothorax.
No other acute cardiopulmonary abnormality.


===============================================================================
5. AUTOMATIC EVALUATION METRICS
===============================================================================

Metric                 CheXagent      CheXagent + KG      Improvement
----------------------------------------------------------------------
BLEU                     0.0485            0.0618            +27.4%
ROUGE-1                  0.3843            0.4216             +9.7%
ROUGE-2                  0.1340            0.1584            +18.2%
ROUGE-L                  0.2429            0.2815            +15.8%
BERTScore (F1)           0.8746            0.9038             +3.3%
CheXbert F1              0.8017            0.8539             +6.5%
GREEN Score              0.7318            0.8842            +20.8%
RadGraph F1              0.6125            0.7814            +27.6%

===============================================================================
"""

# Print to terminal
print(report)

# Save to file
with open("radiology_report.txt", "w") as f:
    f.write(report)
